// Generated by CoffeeScript 1.4.0
(function() {
  var Display, Flickr, Toggle,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $(document).ready(function() {
    new Toggle;
    return new Display;
  });

  /* --------------------------------------------
       Begin toggle.coffee
  --------------------------------------------
  */


  Toggle = (function() {

    function Toggle() {
      this.toggle = __bind(this.toggle, this);
      this.init();
    }

    Toggle.prototype.init = function() {
      this.getElements();
      return this.attachEvents();
    };

    Toggle.prototype.getElements = function() {
      return this.elements = {
        toggle: $('#info-toggle'),
        el: $('#header')
      };
    };

    Toggle.prototype.attachEvents = function() {
      return this.elements.toggle.on('click', this.toggle);
    };

    Toggle.prototype.toggle = function(e) {
      e.preventDefault();
      this.elements.el.toggleClass('header-open');
      return this.elements.toggle.toggleClass('sp-i-icon-hover');
    };

    return Toggle;

  })();

  /* --------------------------------------------
       Begin display.coffee
  --------------------------------------------
  */


  Display = (function() {

    function Display() {
      this.elements = {
        photos: $('#photo-container'),
        sets: $('#sets')
      };
      this.flickr = new Flickr;
      this.init();
    }

    Display.prototype.init = function() {};

    return Display;

  })();

  /* --------------------------------------------
       Begin flickr.coffee
  --------------------------------------------
  */


  Flickr = (function() {

    function Flickr() {
      this.base = 'http://api.flickr.com/services/rest/?method=';
      this.method = 'flickr.photosets.getPhotos';
      this.format = 'json';
      this.apiKey = TAKEN.apiKey;
      this.username = TAKEN.username;
      this.userId = TAKEN.userId;
      this.photoSetId = TAKEN.photoSetId;
      this.url = "" + this.base + this.method + "&api_key=" + this.apiKey + "&photoset_id=" + this.photoSetId + "&extras=date_taken,url_l&format=" + this.format + "&nojsoncallback=1";
    }

    Flickr.prototype.getPhotos = function(cb) {
      return $.ajax({
        url: this.url,
        dataType: 'json',
        success: function(res) {
          if (res.stat === 'ok') {
            return cb(res);
          }
        }
      });
    };

    return Flickr;

  })();

}).call(this);
