// Generated by CoffeeScript 1.4.0
(function() {
  var Toggle,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $(document).ready(function() {
    return new Toggle;
  });

  /* --------------------------------------------
       Begin toggle.coffee
  --------------------------------------------
  */


  Toggle = (function() {

    function Toggle() {
      this.toggle = __bind(this.toggle, this);
      this.init();
    }

    Toggle.prototype.init = function() {
      this.getElements();
      return this.attachEvents();
    };

    Toggle.prototype.getElements = function() {
      return this.elements = {
        toggle: $('#info-toggle'),
        el: $('#header')
      };
    };

    Toggle.prototype.attachEvents = function() {
      return this.elements.toggle.on('click', this.toggle);
    };

    Toggle.prototype.toggle = function(e) {
      e.preventDefault();
      this.elements.el.toggleClass('header-open');
      return this.elements.toggle.toggleClass('sp-i-icon-hover');
    };

    return Toggle;

  })();

}).call(this);
